version: "3.9"

services:
  db:
    image: postgres:16
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  backend:
    image: ghcr.io/rajatrathor/blueorng-backend:latest
    env_file:
      - ./backend/.env.production
    restart: always
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/rajatrathor/blueorng-frontend:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

volumes:
  db_data_prod:
