version: "3.9"

services:
  db:
    image: postgres:16
    volumes:
      - db_data_staging:/var/lib/postgresql/data

  backend:
    image: ghcr.io/rajatrathor/blueorng-backend:latest
    env_file:
      - ./backend/.env.staging
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/rajatrathor/blueorng-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data_staging:
